DO_DBG(SB_COMMAND_O)
DO_DBG(MEM_REQ) 
DO_DBG(VP_SCORE) 
DO_DBG(RISCV_INSTS)
DO_DBG(SB_COMMAND) 
DO_DBG(SB_COMMAND_I)
DO_DBG(SB_COMP)
DO_DBG(VP_SCORE2)
DO_DBG(CYC_STAT)   
DO_DBG(SCR_ACC)    
DO_DBG(SCR_BARRIER)
DO_DBG(SB_MEM_RD)
DO_DBG(SB_MEM_WR)
DO_DBG(SB_WAIT)
DO_DBG(SB_CONTEXT)
DO_DBG(SB_ROI)
DO_DBG(SB_BLAME)
DO_DBG(SHOW_CONFIG)
DO_DBG(ACC_INDEX)



DO_DBG(SUPRESS_SB_STATS)

DO_DBG(VERIF_MEM)
DO_DBG(VERIF_PORT)
DO_DBG(VERIF_CGRA)
DO_DBG(VERIF_SCR)
DO_DBG(VERIF_CMD)
DO_DBG(VERIF_CGRA_MULTI)

DO_DBG(CHECK_SCR_ALIAS)

DO_DBG(UNREAL_INPUTS)
